apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool1
spec:
  addresses:
  - 192.168.2.201-192.168.2.210

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2example
spec:
  ipAddressPools:
  - pool1
