apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n3 
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "N3",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.2.0/24",
        "rangeStart": "192.168.2.241",
        "rangeEnd": "192.168.2.252",
        "gateway": "192.168.2.1"
      }
    }'
